# -*- coding: utf-8 -*-
"""Ass3_Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iTlWDDxXij1kZ_FuhwtwEieJsr03E71
"""

from gui import AIApp

if __name__ == "__main__":
    app = AIApp()
    app.mainloop()