# -*- coding: utf-8 -*-
"""Ass3_Decorators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glmX-9UGXTHa9FDCY0JoHSJ7v2JbGD0D
"""

def uppercase(func):
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs).upper()
    return wrapper

def exclaim(func):
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs) + "!!!"
    return wrapper