# -*- coding: utf-8 -*-
"""Ass3_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSv8YPukOJ1Ieme3kDs2Dg3WjtYnVU97
"""

import os
import torch
from transformers import pipeline
from diffusers import StableDiffusionPipeline
from PIL import Image

class AIModels:
    def __init__(self):
        self._init_models()
        if not os.path.exists("outputs"):
            os.makedirs("outputs")

    def _init_models(self):
        # Text classification
        self.text_classifier = pipeline(
            "text-classification",
            model="distilbert-base-uncased-finetuned-sst-2-english"
        )
        # Text-to-Image generation
        self.image_generator = StableDiffusionPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5",
            torch_dtype=torch.float32
        )

    def generate_image(self, prompt):
        img = self.image_generator(prompt).images[0]
        img_path = f"outputs/generated_image.png"
        img.save(img_path)
        return img_path

    def classify_text(self, text):
        return self.text_classifier(text)[0]